# Generated by Django 6.0.6 on 2026-07-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_setting_alter_answer_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.JSONField(),
        ),
    ]
