# Generated by Django 6.0.6 on 2026-07-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_documentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='extracted_text',
        ),
        migrations.AddField(
            model_name='document',
            name='content_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
