# Generated by Django 6.0.6 on 2026-07-14 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentimage',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
