# Generated by Django 6.0.6 on 2026-07-14 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_documentimage_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='core.quiz'),
        ),
    ]
