# Generated by Django 6.0.6 on 2026-07-14 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_quizattempt_reference_alter_quizattempt_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.documentimage'),
        ),
    ]
