# Generated by Django 6.0.6 on 2026-07-15 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='current_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.documentimage'),
        ),
    ]
