# Generated by Django 6.0.6 on 2026-07-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_quizattempt_current_index_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='questions_generated',
            field=models.BooleanField(default=False),
        ),
    ]
