# Generated by Django 6.0.6 on 2026-07-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_quizattempt_questions_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='reasoning',
            field=models.TextField(blank=True, default=''),
        ),
    ]
