# Generated by Django 6.0.6 on 2026-07-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_quizattempt_difficulty_quizattempt_thinking_effort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='score',
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='difficulty',
            field=models.CharField(choices=[('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=8),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='thinking_effort',
            field=models.CharField(choices=[('thinking', 'Thinking'), ('non-thinking', 'Nonthinking')], default='thinking', max_length=15),
        ),
    ]
